### ISSUE TITLE
Cannot map control to OOB address fields

### ISSUE THREAD

**Issue by akill25445** [acieslik/PCF.BingAddressAutocomplete#1]
This control worked fine on custom address fields which are Single Line of Text, but did not display the OOB address fields to map with.

**Comment by SteveTe** [comment]
Not being able to address the OOB address fields is a know bug raised with Microsoft: 
Work around: 
https://www.magnetismsolutions.com/blog/jaredjohnson/2019/07/04/binding-to-address-fields-in-a-pcf-control
